version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'Bookable'
      MYSQL_USER: 'node'
      MYSQL_PASSWORD: 'bookable'
      MYSQL_ROOT_PASSWORD: 'bookable'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

      
  postgres:
    container_name: PostgreSQL
    restart: always
    image: "postgres" 
    ports:
      - '5432:5432'
    environment: 
      POSTGRES_USER: 'ranga'
      POSTGRES_PASSWORD: 'qwerty'
      POSTGRES_DB: raz
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data: 
  my-db: 
